# HEMANG MALIK (220968092)
#### Lab-2 : Data Preprocessing

In [4]:
import pandas as pd

df = pd.read_excel("Cereals1.xls")  
df

ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.

In [2]:
df.describe()

,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
count,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000
mean,107.368421,2.526316,1.013158,160.065789,2.048684,14.723684,6.934211,93.657895,28.289474,2.197368,1.030000,0.827500,42.327057
std,19.139378,1.089020,1.013159,84.318813,2.219038,4.160444,4.473136,68.502565,22.487813,0.832982,0.151438,0.227204,13.820602
min,50.000000,1.000000,0.000000,0.000000,0.000000,-1.000000,-1.000000,-1.000000,0.000000,1.000000,0.500000,0.250000,18.042851
25%,100.000000,2.000000,0.000000,132.500000,0.750000,12.000000,3.000000,40.000000,25.000000,1.000000,1.000000,0.670000,32.932466
50%,110.000000,2.500000,1.000000,180.000000,1.750000,14.500000,7.000000,90.000000,25.000000,2.000000,1.000000,0.750000,40.253086
75%,110.000000,3.000000,2.000000,212.500000,3.000000,17.000000,11.000000,120.000000,25.000000,3.000000,1.000000,1.000000,50.780847
max,160.000000,6.000000,5.000000,320.000000,14.000000,23.000000,15.000000,330.000000,100.000000,3.000000,1.500000,1.500000,93.704912

In [45]:
df['potass'].mean()

93.65789473684211

In [5]:
df=df.mask(df==-1).fillna(df[['protein','fat','sodium','fiber','carbo','sugars','potass','vitamins']].mean())
df

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100%_Natural_Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.000000,0,3,1.0,1.00,33.983679
1,All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.000000,25,3,1.0,0.33,59.425505
2,All-Bran_with_Extra_Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.000000,25,3,1.0,0.50,93.704912
3,Almond_Delight,R,C,110,2,2,200,1.0,14.0,8.0,93.657895,25,3,1.0,0.75,34.384843
4,Apple_Cinnamon_Cheerios,G,C,110,2,2,180,1.5,10.5,10.0,70.000000,25,1,1.0,0.75,29.509541
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,Triples,G,C,110,2,1,250,0.0,21.0,3.0,60.000000,25,3,1.0,0.75,39.106174
72,Trix,G,C,110,1,1,140,0.0,13.0,12.0,25.000000,25,2,1.0,1.00,27.753301
73,Wheat_Chex,R,C,100,3,1,230,3.0,17.0,3.0,115.000000,25,1,1.0,0.67,49.787445
74,Wheaties,G,C,100,3,1,200,3.0,17.0,3.0,110.000000,25,1,1.0,1.00,51.592193
75,Wheaties_Honey_Gold,G,C,110,2,1,200,1.0,16.0,8.0,60.000000,25,1,1.0,0.75,36.187559

In [6]:
df.describe()

,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
count,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000
mean,107.368421,2.526316,1.013158,160.065789,2.048684,14.930575,7.038608,96.148892,28.289474,2.197368,1.030000,0.827500,42.327057
std,19.139378,1.089020,1.013159,84.318813,2.219038,3.737575,4.377048,66.688658,22.487813,0.832982,0.151438,0.227204,13.820602
min,50.000000,1.000000,0.000000,0.000000,0.000000,7.000000,0.000000,15.000000,0.000000,1.000000,0.500000,0.250000,18.042851
25%,100.000000,2.000000,0.000000,132.500000,0.750000,12.000000,3.000000,43.750000,25.000000,1.000000,1.000000,0.670000,32.932466
50%,110.000000,2.500000,1.000000,180.000000,1.750000,14.861842,7.000000,90.000000,25.000000,2.000000,1.000000,0.750000,40.253086
75%,110.000000,3.000000,2.000000,212.500000,3.000000,17.000000,11.000000,120.000000,25.000000,3.000000,1.000000,1.000000,50.780847
max,160.000000,6.000000,5.000000,320.000000,14.000000,23.000000,15.000000,330.000000,100.000000,3.000000,1.500000,1.500000,93.704912

In [14]:
Q1=df.quantile(q=0.25)
Q3=df.quantile(q=0.75)
IQR=Q3-Q1
print(IQR)

calories    10.000000
protein      1.000000
fat          2.000000
sodium      80.000000
fiber        2.250000
carbo        5.000000
sugars       8.000000
potass      76.250000
vitamins     0.000000
shelf        2.000000
weight       0.000000
cups         0.330000
rating      17.848381
dtype: float64

In [18]:
df=df.mask(df>(1.5*IQR+Q3)).fillna(df[['protein','fat','sodium','fiber','carbo','sugars','potass','vitamins']].median())
df=df.mask(df<(Q1-1.5*IQR)).fillna(df[['protein','fat','sodium','fiber','carbo','sugars','potass','vitamins']].median())

df

C:\Users\mca\AppData\Local\Temp\ipykernel_3576\1794503750.py:1: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version. Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  df=df.mask(df>(1.5*IQR+Q3)).fillna(df[['protein','fat','sodium','fiber','carbo','sugars','potass','vitamins']].median())
C:\Users\mca\AppData\Local\Temp\ipykernel_3576\1794503750.py:2: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version. Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  df=df.mask(df<(Q1-1.5*IQR)).fillna(df[['protein','fat','sodium','fiber','carbo','sugars','potass','vitamins']].median())

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100%_Natural_Bran,Q,C,120.0,3.00,5,180.0,2.00,14.861842,8.0,135.000000,25.0,3,1.0,1.00,33.983679
1,All-Bran,K,C,NaN,4.00,1,260.0,1.75,14.861842,5.0,90.000000,25.0,3,1.0,NaN,59.425505
2,All-Bran_with_Extra_Fiber,K,C,NaN,4.00,0,140.0,1.75,14.861842,0.0,90.000000,25.0,3,1.0,NaN,NaN
3,Almond_Delight,R,C,110.0,2.00,2,200.0,1.00,14.000000,8.0,93.657895,25.0,3,1.0,0.75,34.384843
4,Apple_Cinnamon_Cheerios,G,C,110.0,2.00,2,180.0,1.50,10.500000,10.0,70.000000,25.0,1,1.0,0.75,29.509541
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,Triples,G,C,110.0,2.00,1,250.0,0.00,21.000000,3.0,60.000000,25.0,3,1.0,0.75,39.106174
72,Trix,G,C,110.0,2.25,1,140.0,0.00,13.000000,12.0,25.000000,25.0,2,1.0,1.00,27.753301
73,Wheat_Chex,R,C,100.0,3.00,1,230.0,3.00,17.000000,3.0,115.000000,25.0,1,1.0,0.67,49.787445
74,Wheaties,G,C,100.0,3.00,1,200.0,3.00,17.000000,3.0,110.000000,25.0,1,1.0,1.00,51.592193
75,Wheaties_Honey_Gold,G,C,110.0,2.00,1,200.0,1.00,16.000000,8.0,60.000000,25.0,1,1.0,0.75,36.187559

In [19]:
df.describe()

,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
count,56.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.0,76.000000,63.0,65.000000,69.000000
mean,108.750000,2.615132,1.013158,192.828947,1.792105,15.291724,7.038608,85.754155,25.0,2.197368,1.0,0.876615,43.398213
std,6.892024,0.619732,1.013159,44.032833,1.520220,3.353972,4.377048,48.049515,0.0,0.832982,0.0,0.162175,11.484091
min,100.000000,2.000000,0.000000,95.000000,0.000000,10.000000,0.000000,15.000000,25.0,1.000000,1.0,0.670000,26.734515
25%,100.000000,2.000000,0.000000,170.000000,0.750000,13.000000,3.000000,43.750000,25.0,1.000000,1.0,0.750000,35.252444
50%,110.000000,2.375000,1.000000,180.000000,1.625000,14.930921,7.000000,90.000000,25.0,2.000000,1.0,1.000000,40.560159
75%,110.000000,3.000000,2.000000,212.500000,3.000000,17.000000,11.000000,110.000000,25.0,3.000000,1.0,1.000000,50.828392
max,120.000000,4.000000,5.000000,320.000000,6.000000,23.000000,15.000000,230.000000,25.0,3.000000,1.0,1.330000,74.472949